from enum import Enum


class ServerMessageType(str, Enum):
    PUBLIC_CHANNEL_ADD = "PUBLIC_CHANNEL_ADD"
    PUBLIC_CHANNEL_UPDATED = "PUBLIC_CHANNEL_UPDATED"
    PUBLIC_CHANNEL_KEY_SHARE = "PUBLIC_CHANNEL_KEY_SHARE"
    USER_ADVERTISE = "USER_ADVERTISE"
    MSG_PUBLIC_CHANNEL = "MSG_PUBLIC_CHANNEL"
    SERVER_DELIVER = "SERVER_DELIVER"


class CustomisedMessageType(str, Enum):
    LIST_REQUEST = "LIST_REQUEST"
    LIST_RESPONSE = "LIST_RESPONSE"
