from enum import Enum


class ServerMessageType(str, Enum):
    PUBLIC_CHANNEL_ADD = "PUBLIC_CHANNEL_ADD"
    PUBLIC_CHANNEL_UPDATED = "PUBLIC_CHANNEL_UPDATED"
    PUBLIC_CHANNEL_KEY_SHARE = "PUBLIC_CHANNEL_KEY_SHARE"
    PUBLIC_MEMBERS_SNAPSHOT = "PUBLIC_MEMBERS_SNAPSHOT"
    USER_ADVERTISE = "USER_ADVERTISE"
    MSG_PUBLIC_CHANNEL = "MSG_PUBLIC_CHANNEL"
    SERVER_DELIVER = "SERVER_DELIVER"
    PUBKEY_REQUEST = "PUBKEY_REQUEST"
    PUBKEY_RESPONSE = "PUBKEY_RESPONSE"


class CustomisedMessageType(str, Enum):
    LIST_REQUEST = "LIST_REQUEST"
    LIST_RESPONSE = "LIST_RESPONSE"


class UserAuthType(str, Enum):
    REGISTER = "LOCAL_REGISTER"
    LOGIN_REQUEST = "LOGIN_REQUEST"
    LOGIN_SUCCESS = "LOGIN_SUCCESS"
    LOGIN_FAIL = "LOGIN_FAIL"

